let leads=[],turmas=[],atual=null;const gestorKey='clinvet_gestor_nome';responsavel.value=localStorage.getItem(gestorKey)||'';
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('view-leads').classList.toggle('hidden',b.dataset.tab!=='leads');document.getElementById('view-turmas').classList.toggle('hidden',b.dataset.tab!=='turmas')});
async function loadAll(){[leads,turmas]=await Promise.all([api('gestaoLeadsListar'),api('gestaoTurmasListar')]);drawLeads();drawTurmas();turmaConversao.innerHTML='<option value="">Selecione...</option>'+turmas.filter(t=>t.status!=='ENCERRADA').map(t=>`<option>${esc(t.nome)}</option>`).join('')}
function fmt(d){return d?new Date(d).toLocaleString('pt-BR'):'—'}function fmtDate(d){return d?new Date(d+'T12:00').toLocaleDateString('pt-BR'):'—'}
function drawLeads(){let q=busca.value.toLowerCase(),s=statusFiltro.value,r=respFiltro.value.toLowerCase(),f=leads.filter(x=>(!q||[x.nome,x.telefone,x.email].some(v=>String(v).toLowerCase().includes(q)))&&(!s||x.status===s)&&(!r||String(x.responsavel).toLowerCase().includes(r)));let counts={};leads.forEach(x=>counts[x.status]=(counts[x.status]||0)+1);metrics.innerHTML=['NOVO','EM_CONTATO','AGUARDANDO','INTERESSADO','MATRICULADO','PERDIDO'].map(k=>`<div class="metric"><small>${k.replace('_',' ')}</small><br><b>${counts[k]||0}</b></div>`).join('');leadsBody.innerHTML=f.map(x=>`<tr class="leadrow" onclick="openLead('${x.id}')"><td><b>${esc(x.nome)}</b><br><small>${esc(x.telefone)} • ${esc(x.email)}</small></td><td>${esc(x.curso)}</td><td><span class="badge2 ${x.status}">${esc(x.status)}</span></td><td>${esc(x.responsavel||'—')}</td><td>${fmt(x.ultimoContatoEm)}</td><td>${fmt(x.criadoEm)}</td></tr>`).join('')||'<tr><td colspan="6">Nenhuma pré-matrícula encontrada.</td></tr>'}
[busca,statusFiltro,respFiltro].forEach(x=>x.oninput=drawLeads);atualizar.onclick=loadAll;
function drawTurmas(){turmasBody.innerHTML=turmas.map(t=>`<tr><td><b>${esc(t.nome)}</b></td><td>${fmtDate(t.dataInicio)}</td><td>${fmtDate(t.dataFim)}</td><td>${esc(t.status)}</td><td><button class="btn secondary" onclick="editTurma('${t.id}')">Editar</button></td></tr>`).join('')||'<tr><td colspan="5">Nenhuma turma cadastrada.</td></tr>'}
novaTurma.onclick=()=>{turmaId.value='';turmaNome.value='';turmaInicio.value='';turmaFim.value='';turmaStatus.value='ATIVA';turmaTitulo.textContent='Nova turma';turmaForm.classList.remove('hidden')};cancelarTurma.onclick=()=>turmaForm.classList.add('hidden');window.editTurma=id=>{let t=turmas.find(x=>x.id===id);turmaId.value=t.id;turmaNome.value=t.nome;turmaInicio.value=t.dataInicio;turmaFim.value=t.dataFim;turmaStatus.value=t.status;turmaTitulo.textContent='Editar turma';turmaForm.classList.remove('hidden')};
salvarTurma.onclick=async()=>{if(!turmaNome.value.trim()||!turmaInicio.value||!turmaFim.value){alert('Preencha nome e datas.');return}await api('gestaoTurmaSalvar',{id:turmaId.value||undefined,nome:turmaNome.value.trim(),dataInicio:turmaInicio.value,dataFim:turmaFim.value,status:turmaStatus.value});turmaForm.classList.add('hidden');await loadAll()};
window.openLead=async id=>{let d=await api('gestaoLeadDetalhe',{id});atual=d.lead;dNome.textContent=atual.nome;dMeta.textContent=[atual.telefone,atual.email,atual.curso].filter(Boolean).join(' • ');dStatus.innerHTML=`<span class="badge2 ${atual.status}">${esc(atual.status)}</span> ${atual.responsavel?'• Responsável: <b>'+esc(atual.responsavel)+'</b>':''}`;historico.innerHTML=d.historico.map(h=>`<div class="event"><b>${esc(h.canal)} • ${esc(h.resultado)}</b><br><small>${fmt(h.criadoEm)} • ${esc(h.responsavel)}</small><div>${esc(h.observacao||'')}</div>${h.proximoFollowUp?'<small>Próximo follow-up: '+fmtDate(h.proximoFollowUp)+'</small>':''}</div>`).join('')||'<p>Nenhum contato registrado ainda.</p>';credenciais.classList.add('hidden');drawer.classList.add('show')};
fechar.onclick=()=>drawer.classList.remove('show');drawer.onclick=e=>{if(e.target===drawer)drawer.classList.remove('show')};
assumir.onclick=async()=>{let r=responsavel.value.trim();if(!r){alert('Informe seu nome.');return}localStorage.setItem(gestorKey,r);try{await api('gestaoLeadAssumir',{id:atual.id,responsavel:r});await loadAll();await openLead(atual.id)}catch(e){alert(e.message)}};
registrarContato.onclick=async()=>{let r=responsavel.value.trim();if(!r){alert('Informe o responsável.');return}localStorage.setItem(gestorKey,r);try{await api('gestaoContatoRegistrar',{id:atual.id,responsavel:r,canal:canal.value,resultado:resultado.value,observacao:observacao.value.trim(),proximoFollowUp:followup.value});observacao.value='';followup.value='';await loadAll();await openLead(atual.id)}catch(e){alert(e.message)}};
matricular.onclick=async()=>{let r=responsavel.value.trim();if(!r||!turmaConversao.value){alert('Informe o responsável e selecione a turma.');return}if(!confirm('Confirmar conversão em matrícula? Será criado acesso ao Portal do Aluno.'))return;try{let d=await api('gestaoMatricular',{id:atual.id,responsavel:r,turma:turmaConversao.value});credenciais.innerHTML=`<b>✓ Matrícula efetivada</b><br>Aluno: ${esc(d.nome)}<br>Matrícula: <b>${esc(d.matricula)}</b><br>Senha temporária: <b>${esc(d.senhaTemporaria)}</b><br>Turma: ${esc(d.turma)}<br><small>Entregue essas credenciais ao aluno para acessar o portal.</small>`;credenciais.classList.remove('hidden');await loadAll()}catch(e){alert(e.message)}};
loadAll();
